### ISSUE TITLE
SDL_PollEvent removes an event from the queue

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#1]
Anything that that calls SDL_PollEvent might steal an event from a different piece of code. EX: I'm listening for both a quit event and a key event, if I poll while listening for the key event, and a quit event has happened, my code listening for the quit event won't know it ever happened.

Solution 1: disable any GameComponents that extend IGenericHID if the wrong kind of event for them is next on the queue. if after all GameComponents have been updated and the event still has not been polled, poll it to remove it, re-enable all the GameComponents extending IGenericHID that were disabled, and repeat. I don't know if this would be a performance impact in the form of latency if lots of events that aren't handled are added to the queue. Like if someone spams the close button but it's not programmed to do anything.

Solution 2: every loop, add all of the events on the queue to a vector. if events are being added faster then they are being taken off (unlikely, as long as no one repeatedly calls SDL_PushEvent repeatedly in their program (maybe have a maximum of 50 events can be copied each loop)), this could cause an infinite loop. Then any class that needs to do something with an event can search through and remove any events from the vector that they need. If there are lots of unused events though, this could cause an unexpected amount of memory to be used up. Perhaps events that are older than 1000 loops (modifiable by the programmer of the game, of course) can be automatically removed.

It seems like Solution 1 negatively impacts performance, and solution 2 negatively impacts memory usage, so that's a tradeoff, unless a better solution presents itself.

**Comment by JenniferPylko** [comment]
Or, a variation of Solution 2 would be to sort the events and put each type into it's own queue (every loop it does SDL_PollEvent a certain maximum number of times, then based on the type of event it puts it into queues named InputQueue, WMQueue, etc)

**Comment by JenniferPylko** [comment]
http://sdl.beuc.net/sdl.wiki/SDL_Event has more information

**Comment by JenniferPylko** [comment]
It seems that there are 3 categories of events: events that should be dealt with automatically (input events, SDL_ResizeEvent, SDL_ExposeEvent), events the user should deal with (SDL_ActiveEvent, SDL_QuitEvent), and events that should be discarded (SDL_SysWMEvent)

**Comment by liam-middlebrook** [comment]
The variation of solution 2 seems the most efficient. That way if a keyboard event is detected it could push the data to Keyboard. A mouse event to mouse and etc. We would then need a separate class for Window, which could give the users a lot more customization options.

**Comment by JenniferPylko** [comment]
XNA calls it GameWindow, but yeah

**Comment by liam-middlebrook** [comment]
MINX Is Not XNA.
