### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by liam-middlebrook** [GearChicken/MINX#13]
All public members MUST be documented.
Most protected members should be documented.
It would be nice if private members were documented.

Feel free to comment below with any questions.

**Comment by JenniferPylko** [comment]
This needs to be resolved (or verified that it is already resolved) before release.

**Comment by JenniferPylko** [comment]
Should MathHelper be documented? It's fairly obvious what all those functions do, but it may look nicer in doxygen if they have at least 1 line of documentation.

**Comment by liam-middlebrook** [comment]
I think it should. Also one-liners of what each math function does may be useful for some people.
