### ISSUE TITLE
Header Generation Script

### ISSUE THREAD

**Issue by liam-middlebrook** [GearChicken/MINX#14]
Create a script that will take all of the header files and place them into a headers folder (While preserving directory structure) This will be useful for portability.

Also change buildProject.sh to remove the header include for `/usr/includes/MINX`: #includes should follow the following format:
`#include <MINX\*.h>`

**Comment by JenniferPylko** [comment]
The include should use a forward slash, to maintain compatibility between operating systems.

**Comment by JenniferPylko** [comment]
isn't this what `make headers` already does?

**Comment by liam-middlebrook** [comment]
This needs to be ported from shell to batch (or just write out a program to do it depending on batch's limits).

**Comment by liam-middlebrook** [comment]
I've implemented this in https://github.com/GearChicken/TestMINXProject/commit/0fbc38607ad3a7649290a0d5f29a7e81d788a87f  I don't think this is an issue for MINX to handle, because once released headers shouldn't change.
