### ISSUE TITLE
Choosing a namespace when creating a MINX project

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#16]
Developers should be able to choose their namespace when they create a project.

**Comment by JenniferPylko** [comment]
This has been fixed in buildProject.sh, now it only needs to be fixed in the Windows MINX Project Builder.

**Comment by liam-middlebrook** [comment]
MINX Project Builder isn't going to be a thing anymore. MINX will be a NuGet project that people will be able to just add into their solutions.
