### ISSUE TITLE
Make the libVLC instance in Game protected or private

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#19]
It doesn't need to be public, we may need to use friends in order to keep Media classes working correctly

**Comment by liam-middlebrook** [comment]
I think for any classes that depend on library instances (font and audio are the only two that currently come to mind) we will use friends. That way we can keep our fields for library instances protected/private and will not need to pass in a variable that a user may not know about when constructing the AudioFile or Font objects.

**Comment by liam-middlebrook** [comment]
libVLC is no longer used by MINX
