### ISSUE TITLE
Rewrite Font::RenderText

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#28]
It's inconsistent that Font does not interact with TextureBatch as Texture2D does. In order to fix this one of two things should be done:
- Create a method in TextureBatch called RenderText (or DrawText, to stay consistent), that takes a font, a string, and all the normal TextureBatch::Draw arguments except the texture.

or 
- Make Font::RenderText return a Texture2D which can be used by TextureBatch to draw.

**Comment by liam-middlebrook** [comment]
I've been working on this a bit, https://github.com/GearChicken/MINX/commit/660a93f3204e34ba80d325eddc44b01aa0c4b91a contains working rendering from a font to a texture.

After finding out how awful Font support is in MINX I've decided to make this a critical issue. Once this is solved 1.0 _should_ be ready. I've made a checklist of what needs to be done for this issue to close:
- [x] Get proper font y-alignment - Individual letters should be aligned on the y axis so they are easily readable.
- [x] Horizontal separation without cutting off letters _possibly a kerning issue_
