### ISSUE TITLE
Texture2D does not compile because Color does not exist

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#4]
error text:

`In file included from src/Graphics/Texture2D.cpp:1:0:
src/Graphics/Texture2D.h:23:72: error: ‘Color’ has not been declared
src/Graphics/Texture2D.cpp: In constructor ‘MINX::Graphics::Texture2D::Texture2D(char*, GLuint, GLuint*, int)’:
src/Graphics/Texture2D.cpp:16:52: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
src/Graphics/Texture2D.cpp: In member function ‘void MINX::Graphics::Texture2D::Draw(int, int)’:
src/Graphics/Texture2D.cpp:83:9: warning: unused variable ‘wScale’ [-Wunused-variable]
src/Graphics/Texture2D.cpp: At global scope:
src/Graphics/Texture2D.cpp:129:85: error: ‘Color’ has not been declared
src/Graphics/Texture2D.cpp: In member function ‘void MINX::Graphics::Texture2D::Draw(int, int, float, float, float, int*)’:
src/Graphics/Texture2D.cpp:138:34: error: request for member ‘R’ in ‘* tintColor’, which is of non-class type ‘int’
src/Graphics/Texture2D.cpp:138:54: error: request for member ‘G’ in ‘* tintColor’, which is of non-class type ‘int’
src/Graphics/Texture2D.cpp:138:74: error: request for member ‘B’ in ‘* tintColor’, which is of non-class type ‘int’
make: *** [src/Graphics/Texture2D.o] Error 1`

**Comment by liam-middlebrook** [comment]
If you look in the directotry structure Color.h and Color.cpp do not exist in MINX/3D. These files will need to be pulled from upstream.

**Comment by JenniferPylko** [comment]
fixed
