### ISSUE TITLE
TextureBatch render to RenderTarget

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#42]
It is likely that a programmer would want to logically separate different textures that are isolated to certain areas of the screen, while this could be done with separate TextureBatches, separate RenderTargets opens the possibility for screenshots with an invisible HUD, among others.

**Comment by liam-middlebrook** [comment]
This is already possible. I've provided an example of how to do it below:

```
//Draw some textures into the batch
texBatch->Draw(myTexture, 10, 100);
texBatch->Draw(myTexture2, 100, 10);

//Change the render target so it will capture the batch
SetRenderTarget(renderTarget, Color(0,0,0,0));

//Draw the batched textures
texBatch->DrawLoadedTextures();

//Change the render target back to the default
SetRenderTarget(NULL, Color(0,0,0,0));
```
