### ISSUE TITLE
Change License 

### ISSUE THREAD

**Issue by liam-middlebrook** [GearChicken/MINX#54]
Thoughts?

**Comment by JenniferPylko** [comment]
I think we should stick with LGPL because developers are still free to modify MINX without publishing their game code, they just have to publish their changes. The biggest difference between the two licenses is that MIT would allow developers to keep their changes to the MINX code private while publishing the binary. At this point that could likely only hurt us.

**Comment by liam-middlebrook** [comment]
My concerns come from the fact that while the LGPL is still a liberal license it has the stigma of rules which may deter some developers.

**Comment by JenniferPylko** [comment]
I think that won't be a problem if we display very prominently in Readme.md what the license actually means for them.

**Comment by liam-middlebrook** [comment]
After looking more carefully through some licenses I think that the zlib/libpng license would be a good fit for MINX. I don't think that its necessary for us to force developers who modify MINX to send their commits upstream. If developers were going to modify MINX in the first place (in any way that is a significant change) I believe that they would make their changes noted and take credit.  I also know that because of certain Non-Disclosure Agreements they may not be able to release their MINX changes back to the public.

**Comment by JenniferPylko** [comment]
I like your idea of the zlib/libpng license, then. It's easy to understand, so I think it mostly speaks for itself:

```
Copyright (c) (year) (copyright holders)
This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.

Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.
```

**Comment by liam-middlebrook** [comment]
I still need to implement it.

**Comment by JenniferPylko** [comment]
Ah, right, oops.
