### ISSUE TITLE
Rename dot and cross products in Vector2

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#58]
Right now they are capitalized incorrectly, and should be changed as follows
dotMultiply --> Dot
crossMultiply --> Cross

**Comment by heroyi** [comment]
do you want it changed as in DotMultiply 

OR

just have the functions named simply Dot?

**Comment by JenniferPylko** [comment]
Just Dot, that looks nicer and more like XNA, so therefore less confusing to people who are familiar with XNA.

**Comment by JenniferPylko** [comment]
Oh, and welcome to MINX!

**Comment by JenniferPylko** [comment]
Sorry @heroyi, I missed it when I merged, could you resubmit your pull requests, but have them merge into the "develop" branch please?

**Comment by JenniferPylko** [comment]
And also, the header and cpp file don't need to be 2 separate pull requests, just 1 is fine.

**Comment by heroyi** [comment]
Hey and thanks! 

Sure. Just give me a sec... I'm new to the git scene haha.

**Comment by heroyi** [comment]
Ok so I think I am getting the hang of this. Let me know if anything goes awry and I do apologize for any inconvenience :/
