### ISSUE TITLE
Add Random to MathHelper

### ISSUE THREAD

**Issue by liam-middlebrook** [GearChicken/MINX#63]
If we have some function in MathHelper that could get a random of `x` precision that could potentially be of some use.

Something like
`(rand() % (int)x) / x` where x is a double.

**Comment by heroyi** [comment]
is x an input?

I submitted a pull request with the changes. I was not sure however of whether to include a time seed in the cpp.

**Comment by liam-middlebrook** [comment]
Yes, x would be a parameter in the function `Random(double x)`
