### ISSUE TITLE
TextureBatch Incompatible with RenderTarget

### ISSUE THREAD

**Issue by liam-middlebrook** [GearChicken/MINX#69]
Right now how TextureBatch draws sprites to the screen it bases values off of `GameWindow::GetWidth()` and `GameWindow::GetHeight()`. This is an issue because not all RenderTargets are going to be the size of the GameWindow.

**Comment by JenniferPylko** [comment]
Do you mean that TextureBatch is offsetting textures incorrectly, or that it is scaling incorrectly when it draws to a RenderTarget?

**Comment by liam-middlebrook** [comment]
It's scaling and offsetting incorrectly, that's due to the projection matrix which is created in each TextureBatch::Draw overload. This line is the cuplrit 

```
projectionMatrix = glm::ortho(1.0f,
(float)GameWindow::GetWidth()-1.0f,
(float)GameWindow::GetHeight()-1.0f,
1.0f);
```

It just needs to be changed in each function overload to account for the active render targets width/height instead of the GameWindow's width/height.
