### ISSUE TITLE
LibVLC doesn't play audio on Linux

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#7]
No errors are outputted,  and all pointers appear to be valid

**Comment by liam-middlebrook** [comment]
I just compiled and ran MINX on my laptop using Ubuntu 13.04x64 I had no issues hearing sound playing. We need to test this in another environment to determine whether it is a MINX bug or a bug on your side.

**Comment by JenniferPylko** [comment]
I find it unlikely that it is a big on my side. I can run other programs that user LibVLC fine.

**Comment by liam-middlebrook** [comment]
For the record the issue was compiling MINX with the -lgorilla library.
