### ISSUE TITLE
Remove GameTime arguments from Game::Update() and Game::Draw()

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#70]
There's already a GetGameTime() method in Game, which returns the private gameTime variable, which is what's passed by Run() to the Update() and Draw() methods anyway.

**Comment by liam-middlebrook** [comment]
Why would we remove `GameTime* gameTime` from Update and Draw? If anything `GetGameTime()`should be removed from Game, because it's unnecessary for the developer to get the gameTime data any time before update or draw are called.

**Comment by JenniferPylko** [comment]
But if we get rid of the the `GameTime* gameTime` argument from `GameComponent::Update()`, then we'd need `GetGameTime()`. Most of the compiler warning when compiling MINX say `Unused variable gameTime`, and this would eliminate that as well as making it look cleaner to developers using MINX. If we remove the argument from `GameComponent::Update()`, then we should probably, for consistency, remove it from `Game::Update()` as well, since GetGameTime would be there anyway. If we remove it from `Game::Update()` we should also remove it from `Game::Draw()`.

**Comment by JenniferPylko** [comment]
Another option would be to make GameTime a singleton class, or have all static members, but I know you find lots of statics ugly.

**Comment by liam-middlebrook** [comment]
I personally think that GameTIme should be doing minimal calculations. A possible way for it to function is that it should just be a struct containing some data about the time elapsed and delta time.

**Comment by JenniferPylko** [comment]
It already functions exactly the same as a struct, it performs so little duty and doesn't make sense as a data type it could probably be merged into Game, but I don't know if that would be a 1.0 worthy change.

**Comment by liam-middlebrook** [comment]
I don't think that it should be merged into game. When developers use MINX they may want to pass time data quickly between classes. If we were to dissolve GameTime into the Game class then developers would lose the ease to quickly pass time data between classes.

**Comment by JenniferPylko** [comment]
I still think that because of the `Game::GetGameTime()` method, it's redundant to have a `GameTime*` argument in Game, and to have it in GameComponent when GameComponents already have a stored Game pointer.

**Comment by liam-middlebrook** [comment]
That's what I don't understand. Why do we have `Game::GetGameTIme()` The only time that the developer should want to get the gameTime data should be inside of the Update or Draw functions anyways. (Or rather higher up on the stack from those functions)

**Comment by JenniferPylko** [comment]
Yeah, I guess my problem is that GameTime seems to both be tied to Game, but is also passed around like it's completely independent. I think in order to make it used the way you want, it should really be either a singleton with a `GetInstance()` method or it should be friends with Game so that Game can instantiate it and pass the only instance to any other classes.

**Comment by liam-middlebrook** [comment]
Why do we have functions for updating the values inside of GameTime in GameTime? To me it makes more sense for GameTime to only contain data and have public accessor methods for retrieving that data. Once it's time to update the GameTime that is stored within Game we can do that within a private function inside of Game or GameTime (GameTime should have Game listed as a friend class). That way we can pass around the pointer (maybe we should pass by reference instead) of GameTime wherever it needs to go.

**Comment by JenniferPylko** [comment]
Yeah, I agree, I'll close this issue and make a new one.
