### ISSUE TITLE
Rewrite GameTime

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#73]
Specifically
- [x] Make GameTime friends with Game
- [x] Make the constructor private so only Game can construct a GameTime
- [x] Make `Update()` private
- [x] Remove `Game::GetGameTime()`

**Comment by liam-middlebrook** [comment]
What milestone do we want to do this for?

**Comment by JenniferPylko** [comment]
1.0 pre-release: it's not a huge change code-wise or feature-wise and required testing to verify functionality is minimal.
