### ISSUE TITLE
Remove inline functions

### ISSUE THREAD

**Issue by JenniferPylko** [GearChicken/MINX#97]
They make debugging a little harder and don't produce a noticeable gain in performance on modern systems. In addition, removing them would make #96 easier to implement.

**Comment by liam-middlebrook** [comment]
I don't think this is a good idea.

**Comment by JenniferPylko** [comment]
Explanation?

**Comment by liam-middlebrook** [comment]
Read about how [inline functions](http://en.wikipedia.org/wiki/Inline_function) work.

**Comment by JenniferPylko** [comment]
I already know that. I'm going to need more explanation.

**Comment by liam-middlebrook** [comment]
There's nothing that states that inline functions have to be in the headers.

**Comment by JenniferPylko** [comment]
Oh, I see. I'll close this issue and make a new one.
